Ji 89 today's serving has ended implementation with unit test
Junkfood-dk/JunkFoodApp pull request #27
Opened 2024-04-11 18:39 UTC by OmarSemou

2024-04-11 18:48 UTC, OmarSemou commented
flutter test fails because the default basic flutter is failing but I figure that we will not be using it in the future, otherwise I will work on fixing the test

2024-04-12 11:31 UTC, allanzigge commented on lib/services/service_time_checker.dart
Why 20.59, not 21.00?

2024-04-12 11:33 UTC, allanzigge requested changes
Approved. 

As agreed we will merge next monday, therefore I put "request change" untill then :)

2024-04-12 11:34 UTC, OmarSemou commented on lib/services/service_time_checker.dart
Because the story states that the message should display from 21 therefore after 20:59

2024-04-18 15:30 UTC, allanzigge approved these changes

2024-04-22 06:27 UTC, merged