Share preferences handles saving an identifier of user and their rating
Junkfood-dk/JunkFoodApp pull request #59
Opened 2024-04-29 21:33 UTC by Maquidos

Shard preferences has no option for saving a guid, therefor a random int of 1000000 was chosen

2024-04-30 08:46 UTC, palleBrandt approved these changes
Ser godt ud

2024-04-30 12:01 UTC, JohanSandager requested changes
Could it work by saving the GUID as a string instead?

2024-05-07 06:16 UTC, palleBrandt approved these changes

2024-05-07 06:16 UTC, JohanSandager approved these changes

2024-05-07 06:16 UTC, merged